package p4_group_8_repo;

/**
 * This enum holds keys that identify specific values of level settings
 * @author hfygk1
 *
 */
public enum LevelKeys {
	AMOUNT_OF_TRACKS,
	SPEED_OF_TRACKS,
	DISTANCE_BETWEEN_TRACKS,
	SIZE_OF_TRACKS,
	AMOUNT_OF_CARS,
	SPEED_OF_CARS,
	DISTANCE_BETWEEN_CARS,
	SIZE_OF_CARS,
	AMOUNT_OF_FAST_CARS,
	SPEED_OF_FAST_CARS,
	DISTANCE_BETWEEN_FAST_CARS,
	SIZE_OF_FAST_CARS,
	AMOUNT_OF_LONG_TRACKS,
	SPEED_OF_LONG_TRACKS,
	DISTANCE_BETWEEN_LONG_TRACKS,
	SIZE_OF_LONG_TRACKS,
	AMOUNT_OF_LOGS,
	SPEED_OF_LOGS,
	DISTANCE_BETWEEN_LOGS,
	SIZE_OF_LOGS,
	AMOUNT_OF_LONG_LOGS,
	SPEED_OF_LONG_LOGS,
	DISTANCE_BETWEEN_LONG_LOGS,
	SIZE_OF_LONG_LOGS,
	AMOUNT_OF_TURTLES,
	SPEED_OF_TURTLES,
	DISTANCE_BETWEEN_TURTLES,
	SIZE_OF_TURTLES,
	AMOUNT_OF_WET_TURTLES,
	SPEED_OF_WET_TURTLES,
	DISTANCE_BETWEEN_WET_TURTLES,
	SIZE_OF_WET_TURTLES,
}
